### ISSUE TITLE
questions about license and NuGet publication

### ISSUE THREAD

**Issue by titobrasolin-ke** [Wootness/FileSystemWatcherAlts#1]
@theXappy Thank you so much for your library, I am evaluating the possibility of using it in a small open source experimental project in collaboration with an Italian public body.

First of all I would like to ask you what the license is.
Then, are you planning to publish a NuGet package?

If the license is sufficiently permissive I can do it myself, possibly after applying some small changes that I need.

Thanks again
Tito

**Comment by theXappy** [comment]
Hey
Thank you for your interest in this project. 
Some thing I need you to know:
1. I wrote this code a few years ago and when only .NET Framework was relevant to me. I have no plans on porting to .NET core and I don't even know if FileSystemWatcher is still problematic in .NET core. I encourage you to check if Microsoft offers a better, modern, alternative than my library for this purpose.
2. I never wrote unit tests for  this project. Nor did I use my library in production before. I can not gurnatee a smooth, errorless, experience with it.
3. The relevant license is MIT
4. I did intend to upload it to nuget a while ago but never got to it. You're the first to show interest so I need to reconsider now. 

If you have interesting changes that others can benefit from, and you are willing to contribute them, I'd happily go over them if you submit a pull request.

**Comment by titobrasolin-ke** [comment]
@theXappy Thanks for your detailed reply.

I have done further research and it seems the standard FileSystemWatcher all in all works fine: the malfunctions reported by some users mostly date back to several years ago, so for the moment I have decided not to use external libraries.

However, your code has helped me a lot to understand how things work and therefore thank you again! I'll let you know if I have any changes to suggest.

Tito
